name: GitHub Classroom Workflow

on:
  push:
    paths-ignore:
      - '.github/**'
      - README.md

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: dell
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
